import binascii
from .base_parser import BaseParser

class AES_CBC_PKCS5(BaseParser):
    MAX_KEY = 256
    MAX_MSG = 256
    MAX_IV  = 16
    MAX_CT  = 256

    def generate_header_start(self):
        return (
            f"/*\n"
            f"* Auto-generated header file for AES-CBC-PKCS5 test vectors\n"
            f"* Derived from Project Wycheproof test vectors\n"
            f"* Generated by the Wycheproof-C parser\n"
            f"* Licensed under the Apache License 2.0\n"
            f"* See Project Wycheproof: https://github.com/google/wycheproof\n"
            f"*/\n\n"
            f"#ifndef TV_AES_CBC_PKCS5_H\n"
            f"#define TV_AES_CBC_PKCS5_H\n\n"
            f"#include <stdint.h>\n\n"
            f"typedef struct {{\n"
            f"    int tc_id;\n"
            f"    const char* comment;\n"
            f"    const char* result;\n"
            f"    const char* flags[3];\n"
            f"    size_t flags_len;\n"
            f"    const uint8_t key[{self.MAX_KEY}];\n"
            f"    size_t key_len;\n"
            f"    const uint8_t iv[{self.MAX_IV}];\n"
            f"    size_t iv_len;\n"
            f"    const uint8_t msg[{self.MAX_MSG}];\n"
            f"    size_t msg_len;\n"
            f"    const uint8_t ct[{self.MAX_CT}];\n"
            f"    size_t ct_len;\n"
            f"}} cbc_pkcs5_test_vector_t;\n\n"
            f"static const cbc_pkcs5_test_vector_t cbc_pkcs5_vectors[] = {{\n"
        )

    def parse_test_group(self, group):
        content = []
        for test in group.get("tests", []):
            tc_id = test["tcId"]
            comment = self.escape_string(test.get("comment", ""))
            flags = test.get("flags", [])
            flags_c = ", ".join(f'"{f}"' for f in flags)
            flags_len = len(flags)

            key_bytes = binascii.unhexlify(test["key"])
            iv_bytes  = binascii.unhexlify(test["iv"])
            msg_bytes = binascii.unhexlify(test["msg"]) if test["msg"] else b""
            ct_bytes  = binascii.unhexlify(test["ct"])

            # Check for overflows
            if len(key_bytes) > self.MAX_KEY:
                print(f"Warning: key length {len(key_bytes)} exceeds limit {self.MAX_KEY} in test case {tc_id}")
            if len(iv_bytes) > self.MAX_IV:
                print(f"Warning: iv length {len(iv_bytes)} exceeds limit {self.MAX_IV} in test case {tc_id}")
            if len(msg_bytes) > self.MAX_MSG:
                print(f"Warning: msg length {len(msg_bytes)} exceeds limit {self.MAX_MSG} in test case {tc_id}")
            if len(ct_bytes) > self.MAX_CT:
                print(f"Warning: ct length {len(ct_bytes)} exceeds limit {self.MAX_CT} in test case {tc_id}")

            result = self.escape_string(test.get("result", ""))

            key_init = ", ".join(f"0x{b:02x}" for b in key_bytes)
            iv_init  = ", ".join(f"0x{b:02x}" for b in iv_bytes)
            msg_init = ", ".join(f"0x{b:02x}" for b in msg_bytes)
            ct_init  = ", ".join(f"0x{b:02x}" for b in ct_bytes)

            content.append(
                f"    {{ {tc_id}, \"{comment}\", \"{result}\", "
                f"{{ {flags_c} }}, {flags_len}, "
                f"{{ {key_init} }}, {len(key_bytes)}, "
                f"{{ {iv_init} }}, {len(iv_bytes)}, "
                f"{{ {msg_init} }}, {len(msg_bytes)}, "
                f"{{ {ct_init} }}, {len(ct_bytes)} }}," 
            )

        return "\n".join(content) + "\n"

    def generate_header_end(self):
        return f"}};\n\n#endif  // TV_AES_CBC_PKCS5_H\n"


class AES_GCM(BaseParser):
    MAX_KEY = 260
    MAX_IV  = 260
    MAX_MSG = 540
    MAX_AAD = 540
    MAX_CT  = 540
    MAX_TAG = 16

    def generate_header_start(self):
        return (
            f"/*\n"
            f"* Auto-generated header file for AES-GCM test vectors\n"
            f"* Derived from Project Wycheproof test vectors\n"
            f"* Generated by the Wycheproof-C parser\n"
            f"* Licensed under the Apache License 2.0\n"
            f"* See Project Wycheproof: https://github.com/google/wycheproof\n"
            f"*/\n\n"
            f"#ifndef TV_AES_GCM_H\n"
            f"#define TV_AES_GCM_H\n\n"
            f"#include <stdint.h>\n\n"
            f"typedef struct {{\n"
            f"    int tc_id;\n"
            f"    const char* comment;\n"
            f"    const char* result;\n"
            f"    const char* flags[2];\n"
            f"    size_t flags_len;\n"
            f"    const uint8_t key[{self.MAX_KEY}];\n"
            f"    size_t key_len;\n"
            f"    const uint8_t iv[{self.MAX_IV}];\n"
            f"    size_t iv_len;\n"
            f"    const uint8_t aad[{self.MAX_AAD}];\n"
            f"    size_t aad_len;\n"
            f"    const uint8_t msg[{self.MAX_MSG}];\n"
            f"    size_t msg_len;\n"
            f"    const uint8_t ct[{self.MAX_CT}];\n"
            f"    size_t ct_len;\n"
            f"    const uint8_t tag[{self.MAX_TAG}];\n"
            f"    size_t tag_len;\n"
            f"}} aes_gcm_test_vector_t;\n\n"
            f"static const aes_gcm_test_vector_t aes_gcm_vectors[] = {{\n"
        )

    def parse_test_group(self, group):
        content = []
        for test in group.get("tests", []):
            tc_id = test["tcId"]
            comment = self.escape_string(test.get("comment", ""))
            flags = test.get("flags", [])
            flags_c = ", ".join(f'"{f}"' for f in flags)
            flags_len = len(flags)

            key_bytes = binascii.unhexlify(test["key"])
            iv_bytes = binascii.unhexlify(test["iv"])
            aad_bytes = binascii.unhexlify(test["aad"]) if test["aad"] else b""
            msg_bytes = binascii.unhexlify(test["msg"]) if test["msg"] else b""
            ct_bytes = binascii.unhexlify(test["ct"]) if test["ct"] else b""
            tag_bytes = binascii.unhexlify(test["tag"])

            # Check for overflows
            if len(key_bytes) > self.MAX_KEY:
                print(f"Warning: key length {len(key_bytes)} exceeds limit {self.MAX_KEY} in test case {tc_id}")
            if len(iv_bytes) > self.MAX_IV:
                print(f"Warning: iv length {len(iv_bytes)} exceeds limit {self.MAX_IV} in test case {tc_id}")
            if len(aad_bytes) > self.MAX_AAD:
                print(f"Warning: aad length {len(aad_bytes)} exceeds limit {self.MAX_AAD} in test case {tc_id}")
            if len(msg_bytes) > self.MAX_MSG:
                print(f"Warning: msg length {len(msg_bytes)} exceeds limit {self.MAX_MSG} in test case {tc_id}")
            if len(ct_bytes) > self.MAX_CT:
                print(f"Warning: ct length {len(ct_bytes)} exceeds limit {self.MAX_CT} in test case {tc_id}")
            if len(tag_bytes) > self.MAX_TAG:
                print(f"Warning: tag length {len(tag_bytes)} exceeds limit {self.MAX_TAG} in test case {tc_id}")

            result = self.escape_string(test.get("result", ""))

            key_init = ", ".join(f"0x{b:02x}" for b in key_bytes)
            iv_init = ", ".join(f"0x{b:02x}" for b in iv_bytes)
            aad_init = ", ".join(f"0x{b:02x}" for b in aad_bytes)
            msg_init = ", ".join(f"0x{b:02x}" for b in msg_bytes)
            ct_init = ", ".join(f"0x{b:02x}" for b in ct_bytes)
            tag_init = ", ".join(f"0x{b:02x}" for b in tag_bytes)

            content.append(
                f"    {{ {tc_id}, \"{comment}\", \"{result}\", "
                f"{{ {flags_c} }}, {flags_len}, "
                f"{{ {key_init} }}, {len(key_bytes)}, "
                f"{{ {iv_init} }}, {len(iv_bytes)}, "
                f"{{ {aad_init} }}, {len(aad_bytes)}, "
                f"{{ {msg_init} }}, {len(msg_bytes)}, "
                f"{{ {ct_init} }}, {len(ct_bytes)}, "
                f"{{ {tag_init} }}, {len(tag_bytes)} }}," 
            )

        return "\n".join(content) + "\n"

    def generate_header_end(self):
        return f"}};\n\n#endif  // TV_AES_GCM_H\n"
