import binascii
from .base_parser import BaseParser

class CHACHA20_POLY1305_BASE(BaseParser):
    def __init__(self, algo_name, struct_name, array_name, **kwargs):
        super().__init__(**kwargs)  # directory_path, output_c_header, target_files

        self.MAX_KEY = 32
        self.MAX_IV  = 32
        self.MAX_AAD = 520
        self.MAX_MSG = 520
        self.MAX_CT  = 520
        self.MAX_TAG = 16
        
        self.algo_name = algo_name
        self.struct_name = struct_name
        self.array_name = array_name

    def generate_header_start(self):
        return (
            f"/*\n"
            f"* Auto-generated header file for {self.algo_name.upper().replace('_', '-') } test vectors\n"
            f"* Derived from Project Wycheproof test vectors\n"
            f"* Generated by the Wycheproof-C parser\n"
            f"*/\n\n"
            f"#ifndef TV_{self.algo_name.upper()}_H\n"
            f"#define TV_{self.algo_name.upper()}_H\n\n"
            f"#include <stdint.h>\n\n"
            f"typedef struct {{\n"
            f"    int tc_id;\n"
            f"    const char* comment;\n"
            f"    const char* result;\n"
            f"    const char* flags[2];\n"
            f"    size_t flags_len;\n"
            f"    const uint8_t key[{self.MAX_KEY}];\n"
            f"    size_t key_len;\n"
            f"    const uint8_t iv[{self.MAX_IV}];\n"
            f"    size_t iv_len;\n"
            f"    const uint8_t aad[{self.MAX_AAD}];\n"
            f"    size_t aad_len;\n"
            f"    const uint8_t msg[{self.MAX_MSG}];\n"
            f"    size_t msg_len;\n"
            f"    const uint8_t ct[{self.MAX_CT}];\n"
            f"    size_t ct_len;\n"
            f"    const uint8_t tag[{self.MAX_TAG}];\n"
            f"    size_t tag_len;\n"
            f"}} {self.struct_name};\n\n"
            f"static const {self.struct_name} {self.array_name}[] = {{\n"
        )

    def parse_test_group(self, group):
        content = []
        for test in group.get("tests", []):
            tc_id = test["tcId"]
            comment = self.escape_string(test.get("comment", ""))
            flags = test.get("flags", [])
            flags_c = ", ".join(f'"{f}"' for f in flags)
            flags_len = len(flags)

            key_bytes = binascii.unhexlify(test["key"])
            iv_bytes = binascii.unhexlify(test["iv"])
            aad_bytes = binascii.unhexlify(test["aad"]) if test["aad"] else b""
            msg_bytes = binascii.unhexlify(test["msg"]) if test["msg"] else b""
            ct_bytes = binascii.unhexlify(test["ct"]) if test["ct"] else b""
            tag_bytes = binascii.unhexlify(test["tag"])

            # Check for overflows
            if len(key_bytes) > self.MAX_KEY:
                print(f"Warning: key length {len(key_bytes)} exceeds limit {self.MAX_KEY} in test case {tc_id}")
            if len(iv_bytes) > self.MAX_IV:
                print(f"Warning: iv length {len(iv_bytes)} exceeds limit {self.MAX_IV} in test case {tc_id}")
            if len(aad_bytes) > self.MAX_AAD:
                print(f"Warning: aad length {len(aad_bytes)} exceeds limit {self.MAX_AAD} in test case {tc_id}")
            if len(msg_bytes) > self.MAX_MSG:
                print(f"Warning: msg length {len(msg_bytes)} exceeds limit {self.MAX_MSG} in test case {tc_id}")
            if len(ct_bytes) > self.MAX_CT:
                print(f"Warning: ct length {len(ct_bytes)} exceeds limit {self.MAX_CT} in test case {tc_id}")
            if len(tag_bytes) > self.MAX_TAG:
                print(f"Warning: tag length {len(tag_bytes)} exceeds limit {self.MAX_TAG} in test case {tc_id}")

            result = self.escape_string(test.get("result", ""))

            key_init = ", ".join(f"0x{b:02x}" for b in key_bytes)
            iv_init = ", ".join(f"0x{b:02x}" for b in iv_bytes)
            aad_init = ", ".join(f"0x{b:02x}" for b in aad_bytes)
            msg_init = ", ".join(f"0x{b:02x}" for b in msg_bytes)
            ct_init = ", ".join(f"0x{b:02x}" for b in ct_bytes)
            tag_init = ", ".join(f"0x{b:02x}" for b in tag_bytes)

            content.append(
                f"    {{ {tc_id}, \"{comment}\", \"{result}\", "
                f"{{ {flags_c} }}, {flags_len}, "
                f"{{ {key_init} }}, {len(key_bytes)}, "
                f"{{ {iv_init} }}, {len(iv_bytes)}, "
                f"{{ {aad_init} }}, {len(aad_bytes)}, "
                f"{{ {msg_init} }}, {len(msg_bytes)}, "
                f"{{ {ct_init} }}, {len(ct_bytes)}, "
                f"{{ {tag_init} }}, {len(tag_bytes)} }}," 
            )

        return "\n".join(content) + "\n"

    def generate_header_end(self):
        return f"}};\n\n#endif  // TV_{self.algo_name.upper()}_H\n"

class CHACHA20_POLY1305(CHACHA20_POLY1305_BASE):
    def __init__(self, **kwargs):
        super().__init__(
            algo_name="chaCha20_poly1305",
            struct_name="chacha20_poly1305_test_vector_t",
            array_name="chacha20_poly1305_vectors",
            **kwargs
        )

class XCHACHA20_POLY1305(CHACHA20_POLY1305_BASE):
    def __init__(self, **kwargs):
        super().__init__(
            algo_name="xchaCha20_poly1305",
            struct_name="xchacha20_poly1305_test_vector_t",
            array_name="xchacha20_poly1305_vectors",
            **kwargs
        )