import binascii
from .base_parser import BaseParser, MaxSizes

class AES_GMAC(BaseParser):
    MAX_KEY = MaxSizes.get("AES_GMAC", "MAX_KEY", 256)
    MAX_IV  = MaxSizes.get("AES_GMAC", "MAX_IV", 16)
    MAX_MSG = MaxSizes.get("AES_GMAC", "MAX_MSG", 280)
    MAX_TAG = MaxSizes.get("AES_GMAC", "MAX_TAG", 16)

    def generate_header_start(self):
        return (
            f"/*\n"
            f"* Auto-generated header file for AES-GMAC test vectors\n"
            f"* Derived from Project Wycheproof test vectors\n"
            f"* Generated by the Wycheproof-C parser\n"
            f"*/\n\n"
            f"#ifndef TV_AES_GMAC_H\n"
            f"#define TV_AES_GMAC_H\n\n"
            f"#include <stdint.h>\n\n"
            f"typedef struct {{\n"
            f"    int tc_id;\n"
            f"    const char* comment;\n"
            f"    const char* result;\n"
            f"    const char* flags[2];\n"
            f"    size_t flags_len;\n"
            f"    const uint8_t key[{self.MAX_KEY}];\n"
            f"    size_t key_len;\n"
            f"    const uint8_t iv[{self.MAX_IV}];\n"
            f"    size_t iv_len;\n"
            f"    const uint8_t msg[{self.MAX_MSG}];\n"
            f"    size_t msg_len;\n"
            f"    const uint8_t tag[{self.MAX_TAG}];\n"
            f"    size_t tag_len;\n"
            f"}} aes_gmac_test_vector_t;\n\n"
            f"static const aes_gmac_test_vector_t aes_gmac_test_vector[] = {{\n"
        )

    def parse_test_group(self, group):
        content = []
        for test in group.get("tests", []):
            tc_id = test["tcId"]
            comment = self.escape_string(test.get("comment", ""))
            flags = test.get("flags", [])
            flags_c = ", ".join(f'"{f}"' for f in flags)
            flags_len = len(flags)

            key_bytes = binascii.unhexlify(test["key"])
            iv_bytes  = binascii.unhexlify(test["iv"]) if test["iv"] else b""
            msg_bytes = binascii.unhexlify(test["msg"]) if test["msg"] else b""
            tag_bytes = binascii.unhexlify(test["tag"])

            # Check for overflows
            if len(key_bytes) > self.MAX_KEY:
                print(f"Warning: key length {len(key_bytes)} exceeds limit {self.MAX_KEY} in test case {tc_id}")
            if len(iv_bytes) > self.MAX_IV:
                print(f"Warning: IV length {len(iv_bytes)} exceeds limit {self.MAX_IV} in test case {tc_id}")
            if len(msg_bytes) > self.MAX_MSG:
                print(f"Warning: msg length {len(msg_bytes)} exceeds limit {self.MAX_MSG} in test case {tc_id}")
            if len(tag_bytes) > self.MAX_TAG:
                print(f"Warning: tag length {len(tag_bytes)} exceeds limit {self.MAX_TAG} in test case {tc_id}")

            result = self.escape_string(test.get("result", ""))

            key_init = ", ".join(f"0x{b:02x}" for b in key_bytes)
            iv_init  = ", ".join(f"0x{b:02x}" for b in iv_bytes)
            msg_init = ", ".join(f"0x{b:02x}" for b in msg_bytes)
            tag_init = ", ".join(f"0x{b:02x}" for b in tag_bytes)

            content.append(
                f"    {{ {tc_id}, \"{comment}\", \"{result}\", "
                f"{{ {flags_c} }}, {flags_len}, "
                f"{{ {key_init} }}, {len(key_bytes)}, "
                f"{{ {iv_init} }}, {len(iv_bytes)}, "
                f"{{ {msg_init} }}, {len(msg_bytes)}, "
                f"{{ {tag_init} }}, {len(tag_bytes)} }},"
            )

        return "\n".join(content) + "\n"

    def generate_header_end(self):
        return f"}};\n\n#endif  // TV_AES_GMAC_H\n"