import binascii
from .base_parser import BaseParser

class HKDFSHA(BaseParser):
    def __init__(self, okm_size, algo_name, struct_name, array_name, **kwargs):
        super().__init__(**kwargs)  # directory_path, output_c_header, target_files
        self.MAX_IKM     = 256
        self.MAX_SALT    = 256
        self.MAX_INFO    = 256
        self.MAX_OKM     = okm_size
        self.algo_name   = algo_name
        self.struct_name = struct_name
        self.array_name  = array_name

    def generate_header_start(self):
        return (
            f"/*\n"
            f"* Auto-generated header file for {self.algo_name.upper().replace("_", "-")} test vectors\n"
            f"* Derived from Project Wycheproof test vectors\n"
            f"* Generated by the Wycheproof-C parser\n"
            f"* Licensed under the Apache License 2.0\n"
            f"* See Project Wycheproof: https://github.com/google/wycheproof\n"
            f"*/\n\n"
            f"#ifndef TV_{self.algo_name.upper()}_H\n"
            f"#define TV_{self.algo_name.upper()}_H\n\n"
            f"#include <stdint.h>\n\n"
            f"typedef struct {{\n"
            f"    int tc_id;\n"
            f"    const char* comment;\n"
            f"    const char* result;\n"
            f"    const char* flags[2];\n"
            f"    size_t flags_len;\n"
            f"    const uint8_t ikm[{self.MAX_IKM}];\n"
            f"    size_t ikm_len;\n"
            f"    const uint8_t salt[{self.MAX_SALT}];\n"
            f"    size_t salt_len;\n"
            f"    const uint8_t info[{self.MAX_INFO}];\n"
            f"    size_t info_len;\n"
            f"    const uint8_t okm[{self.MAX_OKM}];\n"
            f"    size_t okm_len;\n"
            f"}} {self.struct_name};\n\n"
            f"static const {self.struct_name} {self.array_name}[] = {{\n"
        )

    def parse_test_group(self, group):
        content = []
        for test in group.get("tests", []):
            tc_id = test["tcId"]
            comment = self.escape_string(test.get("comment", ""))
            flags = test.get("flags", [])
            flags_c = ", ".join(f'"{f}"' for f in flags)
            flags_len = len(flags)

            ikm_bytes = binascii.unhexlify(test["ikm"])
            salt_bytes = binascii.unhexlify(test["salt"]) if test["salt"] else b""
            info_bytes = binascii.unhexlify(test["info"]) if test["info"] else b""
            okm_bytes = binascii.unhexlify(test["okm"])
            okm_len = test["size"]

            # Check for overflows
            if len(ikm_bytes) > self.MAX_IKM:
                print(f"Warning: IKM length {len(ikm_bytes)} exceeds limit {self.MAX_IKM} in test case {tc_id}")
            if len(salt_bytes) > self.MAX_SALT:
                print(f"Warning: Salt length {len(salt_bytes)} exceeds limit {self.MAX_SALT} in test case {tc_id}")
            if len(info_bytes) > self.MAX_INFO:
                print(f"Warning: info length {len(info_bytes)} exceeds limit {self.MAX_INFO} in test case {tc_id}")
            if len(okm_bytes) > self.MAX_OKM:
                print(f"Warning: OKM length {len(okm_bytes)} exceeds limit {self.MAX_OKM} in test case {tc_id}")

            result = self.escape_string(test.get("result", ""))

            ikm_init = ", ".join(f"0x{b:02x}" for b in ikm_bytes)
            salt_init = ", ".join(f"0x{b:02x}" for b in salt_bytes)
            info_init = ", ".join(f"0x{b:02x}" for b in info_bytes)
            okm_init = ", ".join(f"0x{b:02x}" for b in okm_bytes)

            content.append(
                f"    {{ {tc_id}, \"{comment}\", \"{result}\", "
                f"{{ {flags_c} }}, {flags_len}, "
                f"{{ {ikm_init} }}, {len(ikm_init)}, "
                f"{{ {salt_init} }}, {len(salt_init)}, "
                f"{{ {info_init} }}, {len(info_bytes)}, "
                f"{{ {okm_init} }}, {okm_len} }},"
            )

        return "\n".join(content) + "\n"

    def generate_header_end(self):
        return f"}};\n\n#endif  // TV_{self.algo_name.upper()}_H\n"
    
class HKDF_SHA1(HKDFSHA):
    def __init__(self, **kwargs):
        super().__init__(
            okm_size=5100,
            algo_name="HKDF_SHA1",
            struct_name="hkdf_sha1_test_vector_t",
            array_name="hkdf_sha1_vectors",
            **kwargs
        )

class HKDF_SHA256(HKDFSHA):
    def __init__(self, **kwargs):
        super().__init__(
            okm_size=8160,
            algo_name="HKDF_SHA256",
            struct_name="hkdf_sha256_test_vector_t",
            array_name="hkdf_sha256_vectors",
            **kwargs
        )

class HKDF_SHA384(HKDFSHA):
    def __init__(self, **kwargs):
        super().__init__(
            okm_size=12240,
            algo_name="HKDF_SHA384",
            struct_name="hkdf_sha384_test_vector_t",
            array_name="hkdf_sha384_vectors",
            **kwargs
        )

class HKDF_SHA512(HKDFSHA):
    def __init__(self, **kwargs):
        super().__init__(
            okm_size=16320,
            algo_name="HKDF_SHA512",
            struct_name="hkdf_sha512_test_vector_t",
            array_name="hkdf_sha512_vectors",
            **kwargs
        )