import binascii
from .base_parser import BaseParser

import binascii
from .base_parser import BaseParser

class HMACSHA(BaseParser):
    def __init__(self, digest_size, algo_name, struct_name, array_name, **kwargs):
        super().__init__(**kwargs)  # directory_path, output_c_header, target_files
        self.MAX_KEY = 256
        self.MAX_MSG = 256
        self.MAX_TAG = digest_size
        self.algo_name = algo_name
        self.struct_name = struct_name
        self.array_name = array_name

    def generate_header_start(self):
        return (
            f"/*\n"
            f"* Auto-generated header file for {self.algo_name.upper().replace("_", "-")} test vectors\n"
            f"* Derived from Project Wycheproof test vectors\n"
            f"* Generated by the Wycheproof-C parser\n"
            f"*/\n\n"
            f"#ifndef TV_{self.algo_name.upper()}_H\n"
            f"#define TV_{self.algo_name.upper()}_H\n\n"
            f"#include <stdint.h>\n\n"
            f"typedef struct {{\n"
            f"    int tc_id;\n"
            f"    const char* comment;\n"
            f"    const char* result;\n"
            f"    const char* flags[2];\n"
            f"    size_t flags_len;\n"
            f"    const uint8_t key[{self.MAX_KEY}];\n"
            f"    size_t key_len;\n"
            f"    const uint8_t msg[{self.MAX_MSG}];\n"
            f"    size_t msg_len;\n"
            f"    const uint8_t tag[{self.MAX_TAG}];\n"
            f"    size_t tag_len;\n"
            f"}} {self.struct_name};\n\n"
            f"static const {self.struct_name} {self.array_name}[] = {{\n"
        )

    def parse_test_group(self, group):
        content = []
        for test in group.get("tests", []):
            tc_id = test["tcId"]
            comment = self.escape_string(test.get("comment", ""))
            flags = test.get("flags", [])
            flags_c = ", ".join(f'"{f}"' for f in flags)
            flags_len = len(flags)

            key_bytes = binascii.unhexlify(test["key"])
            msg_bytes = binascii.unhexlify(test["msg"]) if test["msg"] else b""
            tag_bytes = binascii.unhexlify(test["tag"])

            # Check for overflows
            if len(key_bytes) > self.MAX_KEY:
                print(f"Warning: key length {len(key_bytes)} exceeds limit {self.MAX_KEY} in test case {tc_id}")
            if len(msg_bytes) > self.MAX_MSG:
                print(f"Warning: msg length {len(msg_bytes)} exceeds limit {self.MAX_MSG} in test case {tc_id}")
            if len(tag_bytes) > self.MAX_TAG:
                print(f"Warning: tag length {len(tag_bytes)} exceeds limit {self.MAX_TAG} in test case {tc_id}")

            result = self.escape_string(test.get("result", ""))

            key_init = ", ".join(f"0x{b:02x}" for b in key_bytes)
            msg_init = ", ".join(f"0x{b:02x}" for b in msg_bytes)
            tag_init = ", ".join(f"0x{b:02x}" for b in tag_bytes)

            content.append(
                f"    {{ {tc_id}, \"{comment}\", \"{result}\", "
                f"{{ {flags_c} }}, {flags_len}, "
                f"{{ {key_init} }}, {len(key_bytes)}, "
                f"{{ {msg_init} }}, {len(msg_bytes)}, "
                f"{{ {tag_init} }}, {len(tag_bytes)} }},"
            )

        return "\n".join(content) + "\n"

    def generate_header_end(self):
        return f"}};\n\n#endif  // TV_{self.algo_name.upper()}_H\n"

class HMACSHA1(HMACSHA):
    def __init__(self, **kwargs):
        super().__init__(
            digest_size=20,
            algo_name="HMAC_SHA1",
            struct_name="hmac_sha1_test_vector_t",
            array_name="hmac_sha1_vectors",
            **kwargs
        )

class HMACSHA224(HMACSHA):
    def __init__(self, **kwargs):
        super().__init__(
            digest_size=28,
            algo_name="hmac_sha224",
            struct_name="hmac_sha224_test_vector_t",
            array_name="hmac_sha224_vectors",
            **kwargs
        )

class HMACSHA256(HMACSHA):
    def __init__(self, **kwargs):
        super().__init__(
            digest_size=32,
            algo_name="hmac_sha256",
            struct_name="hmac_sha256_test_vector_t",
            array_name="hmac_sha256_vectors",
            **kwargs
        )

class HMACSHA384(HMACSHA):
    def __init__(self, **kwargs):
        super().__init__(
            digest_size=48,
            algo_name="hmac_sha384",
            struct_name="hmac_sha384_test_vector_t",
            array_name="hmac_sha384_vectors",
            **kwargs
        )

class HMACSHA512(HMACSHA):
    def __init__(self, **kwargs):
        super().__init__(
            digest_size=64,
            algo_name="hmac_sha512",
            struct_name="hmac_sha512_test_vector_t",
            array_name="hmac_sha512_vectors",
            **kwargs
        )

class HMACSHA3_224(HMACSHA):
    def __init__(self, **kwargs):
        super().__init__(
            digest_size=28,
            algo_name="hmac_sha3_224",
            struct_name="hmac_sha3_224_test_vector_t",
            array_name="hmac_sha3_224_vectors",
            **kwargs
        )

class HMACSHA3_256(HMACSHA):
    def __init__(self, **kwargs):
        super().__init__(
            digest_size=32,
            algo_name="hmac_sha3_256",
            struct_name="hmac_sha3_256_test_vector_t",
            array_name="hmac_sha3_256_vectors",
            **kwargs
        )

class HMACSHA3_384(HMACSHA):
    def __init__(self, **kwargs):
        super().__init__(
            digest_size=48,
            algo_name="hmac_sha3_384",
            struct_name="hmac_sha3_384_test_vector_t",
            array_name="hmac_sha3_384_vectors",
            **kwargs
        )

class HMACSHA3_512(HMACSHA):
    def __init__(self, **kwargs):
        super().__init__(
            digest_size=64,
            algo_name="hmac_sha3_512",
            struct_name="hmac_sha3_512_test_vector_t",
            array_name="hmac_sha3_512_vectors",
            **kwargs
        )