import binascii
from .base_parser import BaseParser

class PBKDF2_HMAC(BaseParser):
    def __init__(self, algo_name, struct_name, array_name, **kwargs):
        super().__init__(**kwargs)  # directory_path, output_c_header, target_files
        self.MAX_PASSWORD = 260
        self.MAX_SALT     = 256
        self.MAX_DK       = 70
        self.algo_name    = algo_name
        self.struct_name  = struct_name
        self.array_name   = array_name

    def generate_header_start(self):
        return (
            f"/*\n"
            f"* Auto-generated header file for {self.algo_name.upper().replace("_", "-")} test vectors\n"
            f"* Derived from Project Wycheproof test vectors\n"
            f"* Generated by the Wycheproof-C parser\n"
            f"* Licensed under the Apache License 2.0\n"
            f"* See Project Wycheproof: https://github.com/google/wycheproof\n"
            f"*/\n\n"
            f"#ifndef TV_{self.algo_name.upper()}_H\n"
            f"#define TV_{self.algo_name.upper()}_H\n\n"
            f"#include <stdint.h>\n\n"
            f"typedef struct {{\n"
            f"    int tc_id;\n"
            f"    const char* comment;\n"
            f"    const char* result;\n"
            f"    const char* flags[3];\n"
            f"    size_t flags_len;\n"
            f"    const uint8_t password[{self.MAX_PASSWORD}];\n"
            f"    size_t password_len;\n"
            f"    const uint8_t salt[{self.MAX_SALT}];\n"
            f"    size_t salt_len;\n"
            f"    size_t iteration_count;\n"
            f"    const uint8_t dk[{self.MAX_DK}];\n"
            f"    size_t dk_len;\n"
            f"}} {self.struct_name};\n\n"
            f"static const {self.struct_name} {self.array_name}[] = {{\n"
        )

    def parse_test_group(self, group):
        content = []
        for test in group.get("tests", []):
            tc_id = test["tcId"]
            comment = self.escape_string(test.get("comment", ""))
            flags = test.get("flags", [])
            flags_c = ", ".join(f'"{f}"' for f in flags)
            flags_len = len(flags)

            password_bytes = binascii.unhexlify(test["password"])
            salt_bytes = binascii.unhexlify(test["salt"]) if test["salt"] else b""
            dk_bytes = binascii.unhexlify(test["dk"])
            dk_len = test["dkLen"]

            # Check for overflows
            if len(password_bytes) > self.MAX_PASSWORD:
                print(f"Warning: Password length {len(password_bytes)} exceeds limit {self.MAX_PASSWORD} in test case {tc_id}")
            if len(salt_bytes) > self.MAX_SALT:
                print(f"Warning: Salt length {len(salt_bytes)} exceeds limit {self.MAX_SALT} in test case {tc_id}")
            if len(dk_bytes) > self.MAX_DK:
                print(f"Warning: DK length {len(dk_bytes)} exceeds limit {self.MAX_DK} in test case {tc_id}")

            iteration_count = test["iterationCount"]
            result = self.escape_string(test.get("result", ""))

            password_init = ", ".join(f"0x{b:02x}" for b in password_bytes)
            salt_init = ", ".join(f"0x{b:02x}" for b in salt_bytes)
            dk_init = ", ".join(f"0x{b:02x}" for b in dk_bytes)

            content.append(
                f"    {{ {tc_id}, \"{comment}\", \"{result}\", "
                f"{{ {flags_c} }}, {flags_len}, "
                f"{{ {password_init} }}, {len(password_bytes)}, "
                f"{{ {salt_init} }}, {len(salt_bytes)}, "
                f"{iteration_count}, "
                f"{{ {dk_init} }}, {dk_len} }},"
            )

        return "\n".join(content) + "\n"

    def generate_header_end(self):
        return f"}};\n\n#endif  // TV_{self.algo_name.upper()}_H\n"
    
class PBKDF2_HMAC_SHA1(PBKDF2_HMAC):
    def __init__(self, **kwargs):
        super().__init__(
            algo_name="PBKDF2_HMAC_SHA1",
            struct_name="pbkdf2_hmac_sha1_test_vector_t",
            array_name="pbkdf2_hmac_sha1_test_vectors",
            **kwargs
        )

class PBKDF2_HMAC_SHA224(PBKDF2_HMAC):
    def __init__(self, **kwargs):
        super().__init__(
            algo_name="PBKDF2_HMAC_SHA224",
            struct_name="pbkdf2_hmac_sha224_test_vector_t",
            array_name="pbkdf2_hmac_sha224_test_vectors",
            **kwargs
        )

class PBKDF2_HMAC_SHA256(PBKDF2_HMAC):
    def __init__(self, **kwargs):
        super().__init__(
            algo_name="PBKDF2_HMAC_SHA256",
            struct_name="pbkdf2_hmac_sha256_test_vector_t",
            array_name="pbkdf2_hmac_sha256_test_vectors",
            **kwargs
        )

class PBKDF2_HMAC_SHA384(PBKDF2_HMAC):
    def __init__(self, **kwargs):
        super().__init__(
            algo_name="PBKDF2_HMAC_SHA384",
            struct_name="pbkdf2_hmac_sha384_test_vector_t",
            array_name="pbkdf2_hmac_sha384_test_vectors",
            **kwargs
        )

class PBKDF2_HMAC_SHA512(PBKDF2_HMAC):
    def __init__(self, **kwargs):
        super().__init__(
            algo_name="PBKDF2_HMAC_SHA512",
            struct_name="pbkdf2_hmac_sha512_test_vector_t",
            array_name="pbkdf2_hmac_sha512_test_vectors",
            **kwargs
        )